---
name: Reporting

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]

jobs:
  codacy:
    name: Codacy coverage
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Test Go code
        run: go test --coverprofile=coverage.out ./...

      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage.out
          language: go
          force-coverage-parser: go
